//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ZMTFixedAssetsWebApp.Domain.Model
{
    public partial class Contractor
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual int nip
        {
            get;
            set;
        }
    
        public virtual string street
        {
            get;
            set;
        }
    
        public virtual string postal_code
        {
            get;
            set;
        }
    
        public virtual string city
        {
            get;
            set;
        }
    
        public virtual string country
        {
            get;
            set;
        }
    
        public virtual string name
        {
            get;
            set;
        }
    
        public virtual string account_number
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<FixedAsset> FixedAssets
        {
            get
            {
                if (_fixedAssets == null)
                {
                    var newCollection = new FixupCollection<FixedAsset>();
                    newCollection.CollectionChanged += FixupFixedAssets;
                    _fixedAssets = newCollection;
                }
                return _fixedAssets;
            }
            set
            {
                if (!ReferenceEquals(_fixedAssets, value))
                {
                    var previousValue = _fixedAssets as FixupCollection<FixedAsset>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupFixedAssets;
                    }
                    _fixedAssets = value;
                    var newValue = value as FixupCollection<FixedAsset>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupFixedAssets;
                    }
                }
            }
        }
        private ICollection<FixedAsset> _fixedAssets;

        #endregion
        #region Association Fixup
    
        private void FixupFixedAssets(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (FixedAsset item in e.NewItems)
                {
                    item.Contractor = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (FixedAsset item in e.OldItems)
                {
                    if (ReferenceEquals(item.Contractor, this))
                    {
                        item.Contractor = null;
                    }
                }
            }
        }

        #endregion
    }
}
