//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ZMTFixedAssetsWebApp.Domain.Model
{
    public partial class Device
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual int id_peripheral_device
        {
            get { return _id_peripheral_device; }
            set
            {
                if (_id_peripheral_device != value)
                {
                    if (PeripheralDevice != null && PeripheralDevice.id != value)
                    {
                        PeripheralDevice = null;
                    }
                    _id_peripheral_device = value;
                }
            }
        }
        private int _id_peripheral_device;
    
        public virtual string serial_number
        {
            get;
            set;
        }
    
        public virtual string ip_address
        {
            get;
            set;
        }
    
        public virtual string mac_address
        {
            get;
            set;
        }
    
        public virtual string producer
        {
            get;
            set;
        }
    
        public virtual string model
        {
            get;
            set;
        }
    
        public virtual string comment
        {
            get;
            set;
        }
    
        public virtual int id_fixed_asset
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual PeripheralDevice PeripheralDevice
        {
            get { return _peripheralDevice; }
            set
            {
                if (!ReferenceEquals(_peripheralDevice, value))
                {
                    var previousValue = _peripheralDevice;
                    _peripheralDevice = value;
                    FixupPeripheralDevice(previousValue);
                }
            }
        }
        private PeripheralDevice _peripheralDevice;

        #endregion
        #region Association Fixup
    
        private void FixupPeripheralDevice(PeripheralDevice previousValue)
        {
            if (previousValue != null && previousValue.Devices.Contains(this))
            {
                previousValue.Devices.Remove(this);
            }
    
            if (PeripheralDevice != null)
            {
                if (!PeripheralDevice.Devices.Contains(this))
                {
                    PeripheralDevice.Devices.Add(this);
                }
                if (id_peripheral_device != PeripheralDevice.id)
                {
                    id_peripheral_device = PeripheralDevice.id;
                }
            }
        }

        #endregion
    }
}
