//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ZMTFixedAssetsWebApp.Domain.Model
{
    public partial class Kind
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual string name
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Licence> Licence
        {
            get
            {
                if (_licence == null)
                {
                    var newCollection = new FixupCollection<Licence>();
                    newCollection.CollectionChanged += FixupLicence;
                    _licence = newCollection;
                }
                return _licence;
            }
            set
            {
                if (!ReferenceEquals(_licence, value))
                {
                    var previousValue = _licence as FixupCollection<Licence>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupLicence;
                    }
                    _licence = value;
                    var newValue = value as FixupCollection<Licence>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupLicence;
                    }
                }
            }
        }
        private ICollection<Licence> _licence;

        #endregion
        #region Association Fixup
    
        private void FixupLicence(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Licence item in e.NewItems)
                {
                    item.Kind = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Licence item in e.OldItems)
                {
                    if (ReferenceEquals(item.Kind, this))
                    {
                        item.Kind = null;
                    }
                }
            }
        }

        #endregion
    }
}
