//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ZMTFixedAssetsWebApp.Domain.Model
{
    public partial class MembershipRole
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual string name
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<MembershipUser> MembershipUser
        {
            get
            {
                if (_membershipUser == null)
                {
                    var newCollection = new FixupCollection<MembershipUser>();
                    newCollection.CollectionChanged += FixupMembershipUser;
                    _membershipUser = newCollection;
                }
                return _membershipUser;
            }
            set
            {
                if (!ReferenceEquals(_membershipUser, value))
                {
                    var previousValue = _membershipUser as FixupCollection<MembershipUser>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupMembershipUser;
                    }
                    _membershipUser = value;
                    var newValue = value as FixupCollection<MembershipUser>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupMembershipUser;
                    }
                }
            }
        }
        private ICollection<MembershipUser> _membershipUser;

        #endregion
        #region Association Fixup
    
        private void FixupMembershipUser(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (MembershipUser item in e.NewItems)
                {
                    if (!item.MembershipRole.Contains(this))
                    {
                        item.MembershipRole.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (MembershipUser item in e.OldItems)
                {
                    if (item.MembershipRole.Contains(this))
                    {
                        item.MembershipRole.Remove(this);
                    }
                }
            }
        }

        #endregion
    }
}
