//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ZMTFixedAssetsWebApp.Domain.Model
{
    public partial class MembershipRole
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual string name
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<MembershipUser> MembershipUsers
        {
            get
            {
                if (_membershipUsers == null)
                {
                    var newCollection = new FixupCollection<MembershipUser>();
                    newCollection.CollectionChanged += FixupMembershipUsers;
                    _membershipUsers = newCollection;
                }
                return _membershipUsers;
            }
            set
            {
                if (!ReferenceEquals(_membershipUsers, value))
                {
                    var previousValue = _membershipUsers as FixupCollection<MembershipUser>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupMembershipUsers;
                    }
                    _membershipUsers = value;
                    var newValue = value as FixupCollection<MembershipUser>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupMembershipUsers;
                    }
                }
            }
        }
        private ICollection<MembershipUser> _membershipUsers;

        #endregion
        #region Association Fixup
    
        private void FixupMembershipUsers(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (MembershipUser item in e.NewItems)
                {
                    if (!item.MembershipRoles.Contains(this))
                    {
                        item.MembershipRoles.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (MembershipUser item in e.OldItems)
                {
                    if (item.MembershipRoles.Contains(this))
                    {
                        item.MembershipRoles.Remove(this);
                    }
                }
            }
        }

        #endregion
    }
}
