//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ZMTFixedAssetsWebApp.Domain.Model
{
    public partial class MembershipUser
    {
        #region Primitive Properties
    
        public virtual string login
        {
            get;
            set;
        }
    
        public virtual string password
        {
            get;
            set;
        }
    
        public virtual string email
        {
            get;
            set;
        }
    
        public virtual string name
        {
            get;
            set;
        }
    
        public virtual string surname
        {
            get;
            set;
        }
    
        public virtual System.DateTime creation_date
        {
            get;
            set;
        }
    
        public virtual System.DateTime last_login_date
        {
            get;
            set;
        }
    
        public virtual bool is_online
        {
            get;
            set;
        }
    
        public virtual bool is_active
        {
            get;
            set;
        }
    
        public virtual Nullable<int> PLKLogin
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Licence> Licence
        {
            get
            {
                if (_licence == null)
                {
                    var newCollection = new FixupCollection<Licence>();
                    newCollection.CollectionChanged += FixupLicence;
                    _licence = newCollection;
                }
                return _licence;
            }
            set
            {
                if (!ReferenceEquals(_licence, value))
                {
                    var previousValue = _licence as FixupCollection<Licence>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupLicence;
                    }
                    _licence = value;
                    var newValue = value as FixupCollection<Licence>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupLicence;
                    }
                }
            }
        }
        private ICollection<Licence> _licence;
    
        public virtual ICollection<MembershipRole> MembershipRole
        {
            get
            {
                if (_membershipRole == null)
                {
                    var newCollection = new FixupCollection<MembershipRole>();
                    newCollection.CollectionChanged += FixupMembershipRole;
                    _membershipRole = newCollection;
                }
                return _membershipRole;
            }
            set
            {
                if (!ReferenceEquals(_membershipRole, value))
                {
                    var previousValue = _membershipRole as FixupCollection<MembershipRole>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupMembershipRole;
                    }
                    _membershipRole = value;
                    var newValue = value as FixupCollection<MembershipRole>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupMembershipRole;
                    }
                }
            }
        }
        private ICollection<MembershipRole> _membershipRole;

        #endregion
        #region Association Fixup
    
        private void FixupLicence(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Licence item in e.NewItems)
                {
                    item.MembershipUser = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Licence item in e.OldItems)
                {
                    if (ReferenceEquals(item.MembershipUser, this))
                    {
                        item.MembershipUser = null;
                    }
                }
            }
        }
    
        private void FixupMembershipRole(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (MembershipRole item in e.NewItems)
                {
                    if (!item.MembershipUser.Contains(this))
                    {
                        item.MembershipUser.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (MembershipRole item in e.OldItems)
                {
                    if (item.MembershipUser.Contains(this))
                    {
                        item.MembershipUser.Remove(this);
                    }
                }
            }
        }

        #endregion
    }
}
