//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ZMTFixedAssetsWebApp.Domain.Model
{
    public partial class Section
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual string name
        {
            get;
            set;
        }
    
        public virtual string short_name
        {
            get;
            set;
        }
    
        public virtual string street
        {
            get;
            set;
        }
    
        public virtual string postal_code
        {
            get;
            set;
        }
    
        public virtual string post
        {
            get;
            set;
        }
    
        public virtual string locality
        {
            get;
            set;
        }
    
        public virtual string phone_number
        {
            get;
            set;
        }
    
        public virtual string email
        {
            get;
            set;
        }

        #endregion
    }
}
