//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ZMTFixedAssetsWebApp.Domain.Model
{
    public partial class Section
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual string name
        {
            get;
            set;
        }
    
        public virtual string short_name
        {
            get;
            set;
        }
    
        public virtual string street
        {
            get;
            set;
        }
    
        public virtual string postal_code
        {
            get;
            set;
        }
    
        public virtual string post
        {
            get;
            set;
        }
    
        public virtual string locality
        {
            get;
            set;
        }
    
        public virtual string phone_number
        {
            get;
            set;
        }
    
        public virtual string email
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Person> People
        {
            get
            {
                if (_people == null)
                {
                    var newCollection = new FixupCollection<Person>();
                    newCollection.CollectionChanged += FixupPeople;
                    _people = newCollection;
                }
                return _people;
            }
            set
            {
                if (!ReferenceEquals(_people, value))
                {
                    var previousValue = _people as FixupCollection<Person>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupPeople;
                    }
                    _people = value;
                    var newValue = value as FixupCollection<Person>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupPeople;
                    }
                }
            }
        }
        private ICollection<Person> _people;

        #endregion
        #region Association Fixup
    
        private void FixupPeople(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Person item in e.NewItems)
                {
                    item.Section = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Person item in e.OldItems)
                {
                    if (ReferenceEquals(item.Section, this))
                    {
                        item.Section = null;
                    }
                }
            }
        }

        #endregion
    }
}
