//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace ZMTFixedAssetsWebApp.Domain.Model
{
    public partial class ZMTdbEntities : ObjectContext
    {
        public const string ConnectionString = "name=ZMTdbEntities";
        public const string ContainerName = "ZMTdbEntities";
    
        #region Constructors
    
        public ZMTdbEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ZMTdbEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ZMTdbEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Contractor> Contractor
        {
            get { return _contractor  ?? (_contractor = CreateObjectSet<Contractor>("Contractor")); }
        }
        private ObjectSet<Contractor> _contractor;
    
        public ObjectSet<Device> Device
        {
            get { return _device  ?? (_device = CreateObjectSet<Device>("Device")); }
        }
        private ObjectSet<Device> _device;
    
        public ObjectSet<FixedAsset> FixedAsset
        {
            get { return _fixedAsset  ?? (_fixedAsset = CreateObjectSet<FixedAsset>("FixedAsset")); }
        }
        private ObjectSet<FixedAsset> _fixedAsset;
    
        public ObjectSet<Kind> Kind
        {
            get { return _kind  ?? (_kind = CreateObjectSet<Kind>("Kind")); }
        }
        private ObjectSet<Kind> _kind;
    
        public ObjectSet<Licence> Licence
        {
            get { return _licence  ?? (_licence = CreateObjectSet<Licence>("Licence")); }
        }
        private ObjectSet<Licence> _licence;
    
        public ObjectSet<MembershipRole> MembershipRole
        {
            get { return _membershipRole  ?? (_membershipRole = CreateObjectSet<MembershipRole>("MembershipRole")); }
        }
        private ObjectSet<MembershipRole> _membershipRole;
    
        public ObjectSet<MembershipUser> MembershipUser
        {
            get { return _membershipUser  ?? (_membershipUser = CreateObjectSet<MembershipUser>("MembershipUser")); }
        }
        private ObjectSet<MembershipUser> _membershipUser;
    
        public ObjectSet<PeripheralDevice> PeripheralDevice
        {
            get { return _peripheralDevice  ?? (_peripheralDevice = CreateObjectSet<PeripheralDevice>("PeripheralDevice")); }
        }
        private ObjectSet<PeripheralDevice> _peripheralDevice;
    
        public ObjectSet<Subgroup> Subgroup
        {
            get { return _subgroup  ?? (_subgroup = CreateObjectSet<Subgroup>("Subgroup")); }
        }
        private ObjectSet<Subgroup> _subgroup;
    
        public ObjectSet<Person> Person
        {
            get { return _person  ?? (_person = CreateObjectSet<Person>("Person")); }
        }
        private ObjectSet<Person> _person;
    
        public ObjectSet<Section> Section
        {
            get { return _section  ?? (_section = CreateObjectSet<Section>("Section")); }
        }
        private ObjectSet<Section> _section;

        #endregion
    }
}
